version: '3.9'
services:
  mongo:
   restart: always
   image: mongo:4.2.0
   volumes:
    - mongo_data:/data/db
   networks:
    - express-mongo
   expose:
      - 27017

  nestjs:
    build: .
    ports:
      - 3000:3000
    stdin_open: true
    restart: always
    networks:
      - express-mongo
    depends_on:
      - mongo

networks:
  express-mongo:

volumes:
  mongo_data: